//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BowlingCalculator.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BowlingCalculator.UI.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View History.
        /// </summary>
        public static string AboutButtonChangelog {
            get {
                return ResourceManager.GetString("AboutButtonChangelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string AboutButtonFeedback {
            get {
                return ResourceManager.GetString("AboutButtonFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate &amp; Review.
        /// </summary>
        public static string AboutButtonRateAndReview {
            get {
                return ResourceManager.GetString("AboutButtonRateAndReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string AboutButtonSupport {
            get {
                return ResourceManager.GetString("AboutButtonSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string AboutButtonWebsite {
            get {
                return ResourceManager.GetString("AboutButtonWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app is licensed under MS-PL. You can contribute to it openly at:.
        /// </summary>
        public static string AboutLicense {
            get {
                return ResourceManager.GetString("AboutLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Player.
        /// </summary>
        public static string AddPlayerButtonText {
            get {
                return ResourceManager.GetString("AddPlayerButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter player&apos;s name.
        /// </summary>
        public static string AddPlayerNameHintText {
            get {
                return ResourceManager.GetString("AddPlayerNameHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Player.
        /// </summary>
        public static string AddPlayerPageTitle {
            get {
                return ResourceManager.GetString("AddPlayerPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Players.
        /// </summary>
        public static string AddPlayerRecentPlayers {
            get {
                return ResourceManager.GetString("AddPlayerRecentPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AppBarAbout {
            get {
                return ResourceManager.GetString("AppBarAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add User.
        /// </summary>
        public static string AppBarAddPlayer {
            get {
                return ResourceManager.GetString("AppBarAddPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string AppBarReset {
            get {
                return ResourceManager.GetString("AppBarReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bowling Calculator.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string ChangelogPageTitle {
            get {
                return ResourceManager.GetString("ChangelogPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        public static string GamePageGetStarted {
            get {
                return ResourceManager.GetString("GamePageGetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a player using the appbar to get started!.
        /// </summary>
        public static string GamePageGetStartedInstructions {
            get {
                return ResourceManager.GetString("GamePageGetStartedInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the scoreboard to keep the same players or start over with new players.
        ///
        ///Hit the back button to cancel..
        /// </summary>
        public static string GamePageResetDialogContent {
            get {
                return ResourceManager.GetString("GamePageResetDialogContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Scores.
        /// </summary>
        public static string GamePageResetDialogLeftButtonContent {
            get {
                return ResourceManager.GetString("GamePageResetDialogLeftButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Over.
        /// </summary>
        public static string GamePageResetDialogRightButtonContent {
            get {
                return ResourceManager.GetString("GamePageResetDialogRightButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset the game.
        /// </summary>
        public static string GamePageResetDialogTitle {
            get {
                return ResourceManager.GetString("GamePageResetDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runner-ups.
        /// </summary>
        public static string GamePageRunnerUps {
            get {
                return ResourceManager.GetString("GamePageRunnerUps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And the winner is....
        /// </summary>
        public static string GamePageWinnerIntro {
            get {
                return ResourceManager.GetString("GamePageWinnerIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pins Knocked Down.
        /// </summary>
        public static string PinPickerDialogTitle {
            get {
                return ResourceManager.GetString("PinPickerDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;releases&gt;  
        ///  &lt;release version=&quot;1.0.0&quot;&gt;
        ///    &lt;notes lang=&quot;en-US&quot;&gt;
        ///    &lt;![CDATA[
        ///- Calculates bowling scores
        ///- Supports any number of players
        ///- Supports Fast Resume
        ///- About page
        ///    ]]&gt;
        ///    &lt;/notes&gt;
        ///  &lt;/release&gt;
        ///&lt;/releases&gt;.
        /// </summary>
        public static string ReleaseNotes {
            get {
                return ResourceManager.GetString("ReleaseNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
    }
}
